### ISSUE TITLE
Can not type traditional Chinese 

### ISSUE THREAD

**Issue by steven130169** [monkeytypegame/monkeytype#4230]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

stevencheng

### Current Behavior

when I use "pinyin" input , I can't type any Chinese word.
like this 
![CleanShot 2023-04-27 at 09 09 21](https://user-images.githubusercontent.com/27000465/234734253-f529b1fa-7094-4a78-92cc-fc087f568b19.png)

### Expected Behavior

because Chinese type need to transcoding, but monkeytype seems not work.
So, my expected is Chinese type transcoding is work.

### Steps To Reproduce

1. chose traditional Chinese type test
2. chose pinyin input source
3. type "taiyang" + space need to show "太陽“，type "baozi" need to show "包子".

### Environment

- OS: Mac OS Ventura 13.3.1
- Browser: Safari 
- Browser Version: 16.4

### Anything else?

none

**Comment by hakujitsu** [comment]
I'm interested in taking this on!

**Comment by hakujitsu** [comment]
I've implemented a basic fix (as shown below), but it's not perfect:

https://user-images.githubusercontent.com/54730257/235821448-420381fb-97ce-46d6-a860-79369ef5b7ed.mov

When typing, the English characters will be partially obscured by the Chinese characters to be typed. Would this be okay?

**Comment by steven130169** [comment]
Yes, I think this is OK! Thanks!

**Comment by ElnuDev** [comment]
The fundamental issue is likely that monkeytype is being impatient and not waiting for the IME composition to finish. One could look into listening for the [`compositionstart`, `compositionupdate`, and `compositionend` events](https://stackoverflow.com/a/37099672), perhaps? The `compositionupdate` fires for all keypresses, however, not just conversion to CJK, so it doesn't fix everything.
